title: Project
preset: page
icon: 🏗

fields:
  type:
    label: Type
    type: select
    options:
      case-study: Case Study
      project: Project
      open-source: Open Source
  link:
    label: Link
    type: text
    required: true
  text:
    label: Text
    type: textarea
    size: medium
    required: true
